### ISSUE TITLE
Ubuntu error when running the script

### ISSUE THREAD

**Issue by baditaflorin** [planemad/osm-history-processor#15]
python get_edits.py 2016-3-3 5

```
mkdir: cannot create directory ‘files’: File exists
# Replication URL http://planet.osm.org/replication/day/000/001/264.osc.gz
100% [....................................................] 493gzip: 264.osc already exists; do you wish to overwrite (y or n)? y
74623 / 49374623# Processing florinbadita_telenav's changes
./osmfilter: 1: ./osmfilter: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "get_edits.py", line 74, in <module>
    if os.path.getsize('{}.osm'.format(user)) > 200 :
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'florinbadita_telenav.osm'
mapuser@map-analyst:/data/files/florinb/cercetare/osm-history-processor$
```

**Comment by baditaflorin** [comment]
osmfilter 264.osc --keep="user=florinbadita_telenav" -o="florinbadita_telenav.osm"
osmfilter Warning: unexpected end of input file: 264.osc

I am trying to debug the error, when i run osmfilter i get this error - unexpected end of input file

This is how the end of file looks like

```
    <member type="way" ref="400520544" role="outer"/>
    <member type="way" ref="400520537" role="outer"/>
    <tag k="admin_level" v="10"/>
    <tag k="boundary" v="administrative"/>
    <tag k="locality" v="townland"/>
    <tag k="name" v="Tonroe Upper"/>
    <tag k="place" v="locality"/>
    <tag k="type" v="boundary"/>
  </relation>
  <relation id="6011994" version="1" timestamp="2016-02-27T23:57:11Z" uid="236361" user="NoelB" changeset="37491702">
    <member type="way" ref="191634739" role="outer"/>
    <member type="way" ref="400520533" role="outer"/>
    <tag k="landuse" v="forest"/>
    <tag k="leaf_cycle" v="evergreen"/>
    <tag k="leaf_type" v="needleleaved"/>
    <tag k="type" v="multipolygon"/>
  </relation>
</create>
```

  </osmChange>

**Comment by planemad** [comment]
@baditaflorin this is strange. Its been a while since i've run it but I recall `Warning: unexpected end of input file` was normal. Are you able to open the file in JOSM?

**Comment by baditaflorin** [comment]
florinb@florinb-VirtualBox:~/telanav/osm-history-processor$ python get_edits.py 2015-8-4 5

# Replication URL http://planet.osm.org/replication/day/000/001/052.osc.gz

100% [....................................................] 48356668 / 48356668# Processing florinbadita_telenav's changes
./osmfilter: 1: ./osmfilter: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "get_edits.py", line 74, in <module>
    if os.path.getsize('{}.osm'.format(user)) > 200 :
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'florinbadita_telenav.osm'
florinb@florinb-VirtualBox:~/telanav/osm-history-processor$

**Comment by baditaflorin** [comment]
I can open the 052.osc file in JOSM

Except this i have a 22 bytes empty zip file edition_052.zip

**Comment by baditaflorin** [comment]
Maybe it can be from some of the import function ? I am trying not to install them with pip install

pip install zipfileDownloading/unpacking zipfile
  Could not find any downloads that satisfy the requirement zipfile
Cleaning up...
No distributions at all found for zipfile
Storing debug log for failure in /home/florinb/.pip/pip.log

**Comment by baditaflorin** [comment]
osmfilter 052.osc --keep="@florinbadita_telenav" -o=florinbadita_telenav.osm
osmfilter Warning: unexpected end of input file: 052.osc

**Comment by baditaflorin** [comment]
This is wierd

Using the --verbose function it seems to work .... 

 osmfilter 052.osc --verbose  --keep="@florinbadita_telenav" -o=florinbadita_telenav.osm
osmfilter: Verbose mode.
osmfilter Parameter: --keep=@florinbadita_telenav
osmfilter: Filter: keep nodes:
osmfilter: Filter:     "@florinbadita_telenav" = "(anything)"
osmfilter: Filter: keep ways:
osmfilter: Filter:     "@florinbadita_telenav" = "(anything)"
osmfilter: Filter: keep relations:
osmfilter: Filter:     "@florinbadita_telenav" = "(anything)"
osmfilter Parameter: -o=florinbadita_telenav.osm
Interrelational hierarchy 1: 0 dependencies.
osmfilter: Relation hierarchies: 0 of maximal 12.
osmfilter Warning: unexpected end of input file: 052.osc
osmfilter: Number of bytes read: 517779606
osmfilter: Last processed: relation 5403273.

**Comment by baditaflorin** [comment]
nop, it`s not working, it`s generating the file, but that is about it

**Comment by baditaflorin** [comment]
do you have any idea how to fix?

**Comment by planemad** [comment]
@baditaflorin just verified this works on my system with my username. Its possible the script is downloading data for days when you do not have any changes, this will produce an empty file.

Can you manually verify the url printed on the terminal has the date for which you are looking for? http://planet.osm.org/replication/day/000/001/

**Comment by baditaflorin** [comment]
python get_edits.py 2016-5-5 60

# Replication URL http://planet.osm.org/replication/day/000/001/272.osc.gz

100% [....................................................] 57171229 / 57171229# Processing Rub21's changes
./osmfilter: 1: ./osmfilter: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "get_edits.py", line 74, in <module>
    if os.path.getsize('{}.osm'.format(user)) > 200 :
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'Rub21.osm'
mapuser@map-analyst:/data/files/florinb/osm-history-processor$

**Comment by baditaflorin** [comment]
i even tried with 600 days, can the script / osm planet daily change can hadle this. i get a 500 MB file 
python get_edits.py 2016-5-5 600

**Comment by planemad** [comment]
@baditaflorin what OS are you on?

**Comment by planemad** [comment]
@baditaflorin would not recommend running for 600 days, since it takes around 5 minutes to just process 1 day. Whats your use case, are you interested in every single edit you have made?

**Comment by baditaflorin** [comment]
@planemad Ubuntu 14.10

First i am interested in making it work. 

i have validated using this user. 
If i just run the command : 
osmfilter 354.osc --keep="@user=andrewpmk" --verbose -o=andrewpmk.osm
It will work. 

But when trying to run the script, i get the usual error 

 python get_edits.py 2016-6-1 50
mkdir: cannot create directory ‘files’: File exists

# Replication URL http://planet.osm.org/replication/day/000/001/309.osc.gz

 99% [.........gzip: 309.osc already exists; do you wish to overwrite (y or n)? y
100% [....................................................] 64438253 / 64438253# Processing florinbadita_telenav's changes
./osmfilter: 1: ./osmfilter: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "get_edits.py", line 74, in <module>
    if os.path.getsize('{}.osm'.format(user)) > 200 :
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'florinbadita_telenav.osm'

**Comment by planemad** [comment]
@baditaflorin ok so this is an OS thing. If you remove the dot slash from `./osmfilter` from https://github.com/planemad/osm-history-processor/blob/master/get_edits.py#L72 it should work

**Comment by baditaflorin** [comment]
@planemad thanks, doing this modification works now. 

I removed the ./ from ./osmfilter

leaving line 72 like this 
bash('osmfilter {}.osc --keep="@user={}" -o={}.osm'.format(ccc, user, user))

I am thinking that for larger sets of days, it can download all of the change files, unite them, and then apply and filter based on the users list. Now it downloads one day, it apply the changes, and then download another day, from what i have seen
