### ISSUE TITLE
the script output nothing at the end

### ISSUE THREAD

**Issue by baditaflorin** [planemad/osm-history-processor#17]
but a bug but a different expectation of what the script do.

**Comment by baditaflorin** [comment]
So the results are individual zip files for each day ?

Ok, that means that it`s working but does not produce the intended result. I will fork and try to see if i can make it do what i want. 

Generate a single file for each of the users that are in the users.list for the given time, so that we can do the peer review process

**Comment by planemad** [comment]
@baditaflorin thats great. This would be convenient if it is configurable, I guess different users have different use cases.
